// ── All translatable content (PT / EN / ES) ───────────────────
// Edit descriptions and labels here; structure lives in skills.js

const translations = {

  // ════════════════════════════════════════════════════════════
  // PORTUGUÊS
  // ════════════════════════════════════════════════════════════
  pt: {
    // ── UI ──
    'profile-role'   : 'Desenvolvedor de sistemas',
    'bio'            : 'Especialização em Engenharia de Software pela UFPR. Atuo do back-end Java/Spring ao front-end React/Angular, com foco em Clean Code, microsserviços e boas práticas.',
    'greeting'       : 'Seja bem-vindo ao meu portfólio',
    'headline'       : 'Olá, sou o <span class="accent">Gustavo</span>',
    'description'    : 'Um entusiasta da área de tecnologia,<br>lhe convido a conhecer um pouco sobre meu trabalho.<br>Participo de projetos desde a <strong>definição das regras de negócio</strong> do "build até o deploy". Tenho sólida experiência com o <strong>back-end Java/Spring</strong> e <strong>front-end JS/React</strong>, com arquiteturas monolíticas e de microsserviços, cloud e boas práticas de engenharia de software.',
    'btn-primary'    : 'Ver Projetos',
    'section-title'  : 'Competências e conhecimentos técnicos',
    'section-subtitle': 'Clique em qualquer tecnologia para entender melhor e ver a documentação',
    'modal-link'     : 'Ver documentação oficial',
    'page-title'     : 'Portfólio — Gustavo Ramos',

    // ── Category names ──
    'Linguagens de Programação' : 'Linguagens de Programação',
    'Bancos de Dados'           : 'Bancos de Dados',
    'Mensageria & Servidores'   : 'Mensageria & Servidores',
    'Autenticação & Segurança'  : 'Autenticação & Segurança',
    'Arquiteturas & Padrões'    : 'Arquiteturas & Padrões',
    'Ferramentas & Metodologias': 'Ferramentas & Metodologias',

    // ── Group labels ──
    'Testes'                : 'Testes',
    'Bibliotecas de UI'     : 'Bibliotecas de UI',
    'Fundamentos Web'       : 'Fundamentos Web',
    'SGBDs Relacionais'     : 'SGBDs Relacionais',
    'Práticas'              : 'Práticas',
    'Versionamento'         : 'Versionamento',
    'Servidores de Aplicação': 'Servidores de Aplicação',
    'Mensageria'            : 'Mensageria',
    'Arquiteturas'          : 'Arquiteturas',
    'Boas Práticas'         : 'Boas Práticas',
    'Gestão Ágil'           : 'Gestão Ágil',
    'Qualidade de Código'   : 'Qualidade de Código',
    'Documentação & Design' : 'Documentação & Design',
    'Colaboração'           : 'Colaboração',
    'Relatórios'            : 'Relatórios',

    // ── Child names that require translation ──
    'Microsserviços'         : 'Microsserviços',
    'Arquitetura Hexagonal'  : 'Arquitetura Hexagonal',
    'Modelagem Relacional'   : 'Modelagem Relacional',
    'Normalização'           : 'Normalização',
    'Otimização de Queries'  : 'Otimização de Queries',
    'Índices e Performance'  : 'Índices e Performance',

    // ── Skill Docs (standalone icon-grid modal) ──
    skillDocs: {
      java:       { name: 'Java 8–25',        desc: 'Linguagem orientada a objetos, fortemente tipada e multiplataforma, base do ecossistema enterprise. Versões 8–17 introduziram lambdas, Streams API, records, sealed classes e pattern matching.', url: 'https://docs.oracle.com/en/java/javase/17/' },
      javascript: { name: 'JavaScript ES6+',  desc: 'Linguagem leve e interpretada essencial para o desenvolvimento web. Suporta programação orientada a objetos, funcional e assíncrona (Promises/async-await). Roda no navegador e no servidor (Node.js).', url: 'https://developer.mozilla.org/pt-BR/docs/Web/JavaScript' },
      typescript: { name: 'TypeScript',       desc: 'Superset tipado do JavaScript desenvolvido pela Microsoft. Adiciona tipagem estática, interfaces, enums e genéricos, tornando projetos de grande escala mais seguros e manuteníveis.', url: 'https://www.typescriptlang.org/docs/' },
      sql:        { name: 'SQL / PL-SQL',     desc: 'SQL é a linguagem padrão para bancos relacionais. PL/SQL é a extensão procedural da Oracle, usada em stored procedures, functions, triggers e pacotes corporativos.', url: 'https://docs.oracle.com/en/database/oracle/oracle-database/21/lnpls/' },
      react:      { name: 'React',            desc: 'Biblioteca JavaScript para construção de interfaces baseadas em componentes reutilizáveis. Criada pelo Meta, usa Virtual DOM; o ecossistema inclui React Router, Context API, hooks e Server Components.', url: 'https://react.dev/' },
      angular:    { name: 'Angular 19',       desc: 'Framework completo para SPAs desenvolvido pelo Google. Inclui injeção de dependência, roteamento, formulários reativos e suporte nativo a TypeScript. A versão 19 traz Signals e control flow nativo.', url: 'https://angular.dev/' },
      hibernate:  { name: 'Hibernate / JPA',  desc: 'Principal implementação da especificação JPA para mapeamento objeto-relacional (ORM) em Java. Abstrai o acesso ao banco, suporta lazy/eager loading, cache de segundo nível e gerenciamento de transações.', url: 'https://hibernate.org/orm/documentation/' },
      jakartaee:  { name: 'Jakarta EE',       desc: 'Plataforma enterprise Java mantida pela Eclipse Foundation (sucessora do Java EE). Agrupa especificações como JSF, EJB, JPA, JAX-RS, CDI e JDBC para desenvolvimento de aplicações corporativas robustas.', url: 'https://jakarta.ee/learn/docs/' }
    },

    // ── Child Meta (accordion child modal) ──
    childMeta: {
      'Spring Boot':       { desc: 'Framework que simplifica a criação de aplicações Java standalone com configuração mínima (convention over configuration). Ideal para microsserviços e APIs REST com servidor embutido Tomcat/Netty.', url: 'https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/' },
      'Spring Security':   { desc: 'Framework de autenticação e autorização para aplicações Spring. Suporta OAuth2, JWT, LDAP e integração com provedores de identidade como Keycloak para controle de acesso granular.', url: 'https://docs.spring.io/spring-security/reference/' },
      'Spring Data JPA':   { desc: 'Módulo do Spring que simplifica o acesso a dados com JPA. Gera implementações de repositórios automaticamente a partir de interfaces, eliminando o boilerplate de persistência.', url: 'https://docs.spring.io/spring-data/jpa/reference/' },
      'Spring MVC':        { desc: 'Framework web MVC do Spring para APIs REST e aplicações web. Baseado no padrão Model-View-Controller com anotações como @RestController, @RequestMapping e @PathVariable.', url: 'https://docs.spring.io/spring-framework/reference/web/webmvc.html' },
      'Spring Cloud':      { desc: 'Conjunto de ferramentas para padrões de sistemas distribuídos: service discovery (Eureka), API Gateway, circuit breaker (Resilience4j), config server e load balancing.', url: 'https://spring.io/projects/spring-cloud' },
      'JSF':               { desc: 'JavaServer Faces — framework MVC orientado a componentes para UIs web em Java EE/Jakarta EE. Base do ecossistema PrimeFaces, com ciclo de vida gerenciado pelo container.', url: 'https://jakarta.ee/specifications/faces/' },
      'EJB':               { desc: 'Enterprise JavaBeans — componentes do lado servidor para lógica de negócios transacional. Suporta beans stateless, stateful e message-driven, gerenciados pelo container Jakarta EE.', url: 'https://jakarta.ee/specifications/enterprise-beans/' },
      'JDBC':              { desc: 'Java Database Connectivity — API padrão do Java para conexão com bancos relacionais via drivers. Base para frameworks ORM como Hibernate e Spring Data JDBC.', url: 'https://docs.oracle.com/en/java/javase/17/docs/api/java.sql/module-summary.html' },
      'JUnit':             { desc: 'Framework de testes unitários mais utilizado no Java. A versão 5 (Jupiter) traz anotações expressivas, extensões, testes parametrizados e suporte nativo ao Java 8+.', url: 'https://junit.org/junit5/docs/current/user-guide/' },
      'Mockito':           { desc: 'Framework de mock para testes em Java. Cria objetos simulados (mocks/stubs/spies) e verifica interações, isolando dependências externas e permitindo testes de unidade precisos.', url: 'https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html' },
      'PrimeFaces':        { desc: 'Biblioteca de componentes ricos para JSF com mais de 100 componentes prontos: tabelas dinâmicas, gráficos, calendários, dialogs e upload de arquivos, com temas personalizáveis.', url: 'https://primefaces.org/documentation/' },
      'Tailwind CSS':      { desc: 'Framework CSS utility-first para estilização diretamente no HTML com classes utilitárias. Elimina CSS customizado excessivo, é altamente configurável e tem suporte nativo a dark mode.', url: 'https://tailwindcss.com/docs/' },
      'Bootstrap':         { desc: 'Framework CSS responsivo com sistema de grid, componentes prontos (navbars, modais, cards, alertas) e utilitários de layout para criação rápida de interfaces consistentes.', url: 'https://getbootstrap.com/docs/' },
      'HTML5':             { desc: 'Quinta versão da linguagem de marcação da web. Introduziu semântica (article, section, header), APIs nativas como Canvas, WebStorage e Geolocation, e melhor suporte a acessibilidade.', url: 'https://developer.mozilla.org/pt-BR/docs/Web/HTML' },
      'CSS3':              { desc: 'Terceira versão das Folhas de Estilo em Cascata. Trouxe flexbox, grid, animações, transições, variáveis CSS e media queries para estilização de interfaces modernas e responsivas.', url: 'https://developer.mozilla.org/pt-BR/docs/Web/CSS' },
      'SPA':               { desc: 'Single Page Application — padrão arquitetural onde uma única página HTML carrega a aplicação inteira, atualizando dinamicamente o conteúdo via JavaScript sem recarregar a página.', url: 'https://developer.mozilla.org/pt-BR/docs/Glossary/SPA' },
      'Oracle':            { desc: 'SGBD relacional líder corporativo com alta escalabilidade, suporte a PL/SQL e recursos avançados como RAC (alta disponibilidade), Data Guard (disaster recovery) e In-Memory.', url: 'https://docs.oracle.com/en/database/oracle/oracle-database/21/' },
      'PostgreSQL':        { desc: 'SGBD relacional open-source mais avançado, com suporte a tipos de dados avançados (JSON, arrays, hstore), extensões como PostGIS e excelente conformidade com SQL padrão.', url: 'https://www.postgresql.org/docs/' },
      'MySQL':             { desc: 'Banco de dados relacional open-source mais utilizado no mundo, amplamente adotado em aplicações web com boa performance, suporte a transactions (InnoDB) e replicação.', url: 'https://dev.mysql.com/doc/' },
      'Modelagem Relacional': { desc: 'Estruturação de dados em tabelas com relacionamentos definidos por chaves primárias e estrangeiras. A base de qualquer banco relacional, garantindo integridade referencial dos dados.', url: 'https://learn.microsoft.com/pt-br/office/troubleshoot/access/database-normalization-description' },
      'Normalização':      { desc: 'Processo de organização de tabelas para reduzir redundância e dependências. Envolve as formas normais (1FN, 2FN, 3FN, BCNF) para garantir consistência e eficiência do banco.', url: 'https://learn.microsoft.com/pt-br/office/troubleshoot/access/database-normalization-description' },
      'Otimização de Queries': { desc: 'Técnicas para melhorar a performance de consultas SQL: uso estratégico de índices, EXPLAIN PLAN, reescrita de queries complexas, evitar N+1 e ajuste de parâmetros do banco.', url: 'https://www.postgresql.org/docs/current/performance-tips.html' },
      'Índices e Performance': { desc: 'Estruturas que aceleram buscas em bancos de dados. Tipos: B-tree, Hash, GIN, BRIN. Uso estratégico evita full table scans e reduz drasticamente o tempo de resposta de queries.', url: 'https://use-the-index-luke.com/' },
      'AWS':               { desc: 'Maior plataforma de cloud do mundo com +200 serviços: EC2 (computação), S3 (armazenamento), RDS (banco gerenciado), Lambda (serverless), EKS (Kubernetes gerenciado) e muito mais.', url: 'https://docs.aws.amazon.com/' },
      'Azure':             { desc: 'Plataforma de cloud da Microsoft com forte integração ao ecossistema .NET e Microsoft 365. Oferece AKS, Azure Functions, Azure DevOps, Active Directory e pipelines de CI/CD.', url: 'https://learn.microsoft.com/pt-br/azure/' },
      'Google Cloud Platform (GCP)': { desc: 'Plataforma de cloud do Google focada em dados e IA. Destaques: BigQuery, Cloud Run, GKE (Kubernetes), Cloud Functions, Vertex AI e integração nativa com Firebase.', url: 'https://cloud.google.com/docs' },
      'Firebase':          { desc: 'Plataforma do Google para desenvolvimento de apps com banco em tempo real (Firestore), autenticação integrada, hosting, cloud functions, storage e analytics.', url: 'https://firebase.google.com/docs' },
      'Docker':            { desc: 'Plataforma de containerização que empacota aplicações e dependências em containers portáveis. Garante consistência entre ambientes dev, staging e produção, facilitando deploys.', url: 'https://docs.docker.com/' },
      'Kubernetes':        { desc: 'Plataforma open-source de orquestração de containers desenvolvida pelo Google. Automatiza deploy, escalonamento horizontal e gerenciamento de aplicações em clusters.', url: 'https://kubernetes.io/docs/home/' },
      'Git':               { desc: 'Sistema de controle de versão distribuído mais utilizado no mundo. Permite rastrear mudanças no código, criar branches, mesclar alterações e colaborar eficientemente em equipe.', url: 'https://git-scm.com/doc' },
      'GitHub':            { desc: 'Maior plataforma de hospedagem de código baseada em Git. Oferece repositórios, pull requests, code review colaborativo, GitHub Actions para CI/CD e GitHub Packages.', url: 'https://docs.github.com/pt' },
      'Bitbucket':         { desc: 'Plataforma de hospedagem de código da Atlassian com integração nativa ao Jira e Confluence. Suporta Git, pipelines de CI/CD integrados e controle de acesso granular por times.', url: 'https://support.atlassian.com/bitbucket-cloud/' },
      'GitHub Actions':    { desc: 'Plataforma de CI/CD integrada ao GitHub. Automatiza workflows de build, testes e deploy com arquivos YAML no repositório, e oferece marketplace de actions reutilizáveis.', url: 'https://docs.github.com/pt/actions' },
      'Azure DevOps':      { desc: 'Suite de DevOps da Microsoft com Boards (gestão ágil), Repos (Git), Pipelines (CI/CD), Test Plans e Artifacts. Forte integração com Azure e ecossistema Microsoft.', url: 'https://learn.microsoft.com/pt-br/azure/devops/' },
      'Pipelines':         { desc: 'Pipelines de CI/CD automatizam o fluxo completo de build, testes e deploy de software. Garantem entrega contínua de qualidade, integrando ferramentas como GitHub Actions e Azure DevOps.', url: 'https://docs.github.com/pt/actions/writing-workflows' },
      'RabbitMQ (AMQP)':   { desc: 'Broker de mensagens open-source que implementa o protocolo AMQP. Permite comunicação assíncrona entre microsserviços com filas, exchanges, roteamento e garantia de entrega de mensagens.', url: 'https://www.rabbitmq.com/documentation.html' },
      'REST APIs':         { desc: 'Arquitetura de APIs baseada nos princípios REST: recursos identificados por URLs, verbos HTTP (GET/POST/PUT/DELETE), stateless e respostas em JSON/XML. Padrão dominante para integração de sistemas.', url: 'https://restfulapi.net/' },
      'Apache HTTP Server':{ desc: 'Servidor web open-source mais utilizado do mundo. Suporta módulos como mod_proxy (proxy reverso), mod_ssl (HTTPS), mod_rewrite (URLs amigáveis) e virtual hosts para múltiplos domínios.', url: 'https://httpd.apache.org/docs/' },
      'WildFly':           { desc: 'Servidor de aplicações Jakarta EE open-source da Red Hat. Suporta EJB, JPA, JAX-RS e CDI. JBoss EAP é a versão enterprise certificada com suporte comercial para produção.', url: 'https://docs.wildfly.org/' },
      'JBoss EAP':         { desc: 'Red Hat JBoss Enterprise Application Platform — versão enterprise do WildFly com suporte Red Hat, patches de segurança, certificações e recursos adicionais para ambientes de produção críticos.', url: 'https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/' },
      'OAuth2':            { desc: 'Protocolo de autorização aberto (RFC 6749) que permite acesso delegado a recursos sem compartilhar credenciais. Padrão para autenticação moderna em APIs REST e Single Page Applications.', url: 'https://oauth.net/2/' },
      'OpenID Connect':    { desc: 'Camada de identidade construída sobre OAuth2 que adiciona autenticação federada. Retorna informações do usuário via ID Token no formato JWT, habilitando SSO entre sistemas.', url: 'https://openid.net/connect/' },
      'SSO':               { desc: 'Single Sign-On — o usuário autentica uma única vez e acessa múltiplos sistemas sem novos logins. Implementado via Keycloak com OpenID Connect para centralizar identidade corporativa.', url: 'https://www.keycloak.org/docs/latest/server_admin/#sso-protocols' },
      'JWT':               { desc: 'JSON Web Token (RFC 7519) — padrão para transmissão segura de informações entre partes como JSON assinado digitalmente. Amplamente usado para autenticação stateless em APIs RESTful.', url: 'https://jwt.io/introduction/' },
      'Role-based Access Control': { desc: 'Controle de acesso baseado em papéis (RBAC): usuários têm permissões atribuídas via roles (ex: ADMIN, USER). Implementado com @PreAuthorize e @Secured no Spring Security.', url: 'https://docs.spring.io/spring-security/reference/servlet/authorization/method-security.html' },
      'Microsserviços':    { desc: 'Estilo arquitetural onde a aplicação é decomposta em serviços pequenos, independentes e deployáveis separadamente. Cada serviço tem sua responsabilidade, banco de dados e ciclo de deploy próprio.', url: 'https://microservices.io/' },
      'Clean Architecture':{ desc: 'Arquitetura proposta por Robert C. Martin que organiza o código em camadas concêntricas (Entities, Use Cases, Adapters, Frameworks), garantindo independência de frameworks, UI e banco de dados.', url: 'https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html' },
      'Arquitetura Hexagonal': { desc: 'Também chamada Ports & Adapters, isola o domínio de suas dependências externas (UI, BD, APIs) por interfaces bem definidas. Facilita troca de implementações e testes de unidade.', url: 'https://alistair.cockburn.us/hexagonal-architecture/' },
      'MVC':               { desc: 'Model-View-Controller — padrão que separa a aplicação em três camadas: Model (dados e regras), View (interface) e Controller (fluxo de controle). Base de frameworks como Spring MVC e Angular.', url: 'https://developer.mozilla.org/en-US/docs/Glossary/MVC' },
      'SOLID':             { desc: 'Cinco princípios de design OO: Single Responsibility, Open/Closed, Liskov Substitution, Interface Segregation e Dependency Inversion. Guia para código coeso, extensível e testável.', url: 'https://www.digitalocean.com/community/conceptual-articles/s-o-l-i-d-the-first-five-principles-of-object-oriented-design' },
      'Clean Code':        { desc: 'Conjunto de práticas para código legível e manutenível, popularizado por Robert C. Martin. Foca em nomes significativos, funções pequenas com responsabilidade única e ausência de duplicação.', url: 'https://www.oreilly.com/library/view/clean-code-a/9780136083238/' },
      'TDD':               { desc: 'Test-Driven Development — metodologia onde o teste é escrito antes do código de produção. Ciclo Red (teste falha) → Green (código mínimo passa) → Refactor (melhoria sem quebrar testes).', url: 'https://martinfowler.com/bliki/TestDrivenDevelopment.html' },
      'BDD':               { desc: 'Behavior-Driven Development — extensão do TDD que descreve comportamentos do sistema em linguagem natural (Gherkin: Given/When/Then). Aproxima desenvolvedores, QA e stakeholders por meio de especificações executáveis.', url: 'https://cucumber.io/docs/bdd/' },
      'Scrum':             { desc: 'Framework ágil iterativo e incremental com papéis (Product Owner, Scrum Master, Dev Team), cerimônias (Planning, Daily, Review, Retrospectiva) e artefatos (Product Backlog, Sprint Backlog).', url: 'https://www.scrum.org/resources/what-is-scrum' },
      'Kanban':            { desc: 'Método ágil de gestão visual do fluxo de trabalho originado na Toyota. Usa quadros com colunas (To Do, In Progress, Done) e limita o WIP (Work in Progress) para maximizar throughput.', url: 'https://www.atlassian.com/br/agile/kanban' },
      'Jira':              { desc: 'Plataforma de gestão de projetos ágeis da Atlassian. Suporta Scrum e Kanban, sprints, backlogs, épicos, relatórios de velocity e integração com CI/CD e repositórios de código.', url: 'https://support.atlassian.com/jira-software-cloud/' },
      'Trello':            { desc: 'Ferramenta visual de gestão de tarefas da Atlassian, baseada em Kanban. Organiza projetos em boards, listas e cards com automações Butler, power-ups e colaboração em tempo real.', url: 'https://support.atlassian.com/trello/' },
      'SonarQube':         { desc: 'Plataforma de inspeção contínua de qualidade de código. Detecta bugs, vulnerabilidades, code smells e calcula dívida técnica. Integra ao CI/CD com Quality Gates automáticos.', url: 'https://docs.sonarqube.org/latest/' },
      'Code Review':       { desc: 'Revisão de código por pares antes do merge. Melhora qualidade, dissemina conhecimento na equipe, identifica bugs precocemente e garante aderência a padrões de codificação.', url: 'https://google.github.io/eng-practices/review/' },
      'Pair Programming':  { desc: "Prática XP onde dois desenvolvedores trabalham juntos: o 'driver' escreve o código e o 'navigator' revisa em tempo real. Reduz erros, acelera aprendizado e melhora a qualidade do código.", url: 'https://martinfowler.com/articles/on-pair-programming.html' },
      'Swagger/OpenAPI':   { desc: 'Ferramentas para design, documentação e teste de APIs REST. A especificação OpenAPI descreve APIs de forma padronizada, gerando documentação interativa e clients automaticamente.', url: 'https://swagger.io/docs/' },
      'Figma':             { desc: 'Ferramenta de design colaborativo em nuvem para criação de interfaces, protótipos e sistemas de design. Permite colaboração em tempo real entre designers e desenvolvedores.', url: 'https://help.figma.com/' },
      'UML':               { desc: 'Unified Modeling Language — linguagem de modelagem padrão para visualizar e documentar sistemas de software com diagramas de classe, sequência, casos de uso, componentes e deploy.', url: 'https://www.uml.org/' },
      'Slack':             { desc: 'Plataforma de comunicação para equipes com canais organizados, mensagens diretas, videochamadas e integração com GitHub, Jira, CI/CD e centenas de ferramentas de desenvolvimento.', url: 'https://slack.com/intl/pt-br/help' },
      'Microsoft Teams':   { desc: 'Plataforma de colaboração da Microsoft integrada ao Office 365. Oferece chat, videochamadas, canais por projeto e integração nativa com SharePoint, OneDrive e Azure DevOps.', url: 'https://learn.microsoft.com/pt-br/microsoftteams/' },
      'Google Workspace':  { desc: 'Suite de produtividade e colaboração do Google com Gmail, Drive, Docs, Sheets, Meet e Calendar. Amplamente utilizada por equipes de desenvolvimento para comunicação e documentação.', url: 'https://workspace.google.com/' },
      'JasperReports':     { desc: 'Biblioteca Java open-source da TIBCO para geração de relatórios em PDF, Excel, HTML e outros formatos a partir de templates JRXML. Integra com Spring e qualquer fonte de dados.', url: 'https://community.jaspersoft.com/documentation/' }
    }
  },

  // ════════════════════════════════════════════════════════════
  // ENGLISH
  // ════════════════════════════════════════════════════════════
  en: {
    // ── UI ──
    'profile-role'   : 'Systems Developer',
    'bio'            : 'Software Engineering specialization at UFPR. I work from Java/Spring back-end to React/Angular front-end, focused on Clean Code, microservices and best practices.',
    'greeting'       : 'Welcome to my portfolio',
    'headline'       : 'Hi, I\'m <span class="accent">Gustavo</span>',
    'description'    : 'A technology enthusiast,<br>I invite you to learn a bit about my work.<br>I participate in projects from <strong>business rule definition</strong> through build to deploy. I have solid experience with <strong>Java/Spring back-end</strong> and <strong>JS/React front-end</strong>, with monolithic and microservices architectures, cloud, and software engineering best practices.',
    'btn-primary'    : 'View Projects',
    'section-title'  : 'Skills and technical knowledge',
    'section-subtitle': 'Click on any technology to learn more and view the documentation',
    'modal-link'     : 'View official documentation',
    'page-title'     : 'Portfolio — Gustavo Ramos',

    // ── Category names ──
    'Linguagens de Programação' : 'Programming Languages',
    'Bancos de Dados'           : 'Databases',
    'Mensageria & Servidores'   : 'Messaging & Servers',
    'Autenticação & Segurança'  : 'Authentication & Security',
    'Arquiteturas & Padrões'    : 'Architectures & Patterns',
    'Ferramentas & Metodologias': 'Tools & Methodologies',

    // ── Group labels ──
    'Testes'                : 'Testing',
    'Bibliotecas de UI'     : 'UI Libraries',
    'Fundamentos Web'       : 'Web Fundamentals',
    'SGBDs Relacionais'     : 'Relational DBMSs',
    'Práticas'              : 'Practices',
    'Versionamento'         : 'Version Control',
    'Servidores de Aplicação': 'Application Servers',
    'Mensageria'            : 'Messaging',
    'Arquiteturas'          : 'Architectures',
    'Boas Práticas'         : 'Best Practices',
    'Gestão Ágil'           : 'Agile Management',
    'Qualidade de Código'   : 'Code Quality',
    'Documentação & Design' : 'Documentation & Design',
    'Colaboração'           : 'Collaboration',
    'Relatórios'            : 'Reports',

    // ── Child names ──
    'Microsserviços'         : 'Microservices',
    'Arquitetura Hexagonal'  : 'Hexagonal Architecture',
    'Modelagem Relacional'   : 'Relational Modeling',
    'Normalização'           : 'Normalization',
    'Otimização de Queries'  : 'Query Optimization',
    'Índices e Performance'  : 'Indexes & Performance',

    // ── Skill Docs ──
    skillDocs: {
      java:       { name: 'Java 8–25',       desc: 'Object-oriented, strongly-typed and cross-platform language, backbone of enterprise development. Versions 8–17 added lambdas, Streams API, records, sealed classes and pattern matching.', url: 'https://docs.oracle.com/en/java/javase/17/' },
      javascript: { name: 'JavaScript ES6+', desc: 'Lightweight interpreted language essential for web development. Supports OOP, functional and async programming (Promises/async-await). Runs in the browser and on the server (Node.js).', url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript' },
      typescript: { name: 'TypeScript',      desc: 'Typed superset of JavaScript by Microsoft. Adds static typing, interfaces, enums and generics — making large-scale projects safer and more maintainable.', url: 'https://www.typescriptlang.org/docs/' },
      sql:        { name: 'SQL / PL-SQL',    desc: "SQL is the standard language for relational databases. PL/SQL is Oracle's procedural extension used in stored procedures, functions, triggers and enterprise packages.", url: 'https://docs.oracle.com/en/database/oracle/oracle-database/21/lnpls/' },
      react:      { name: 'React',           desc: 'JavaScript library for building UIs with reusable components. Created by Meta, uses Virtual DOM; the ecosystem includes React Router, Context API, hooks and Server Components.', url: 'https://react.dev/' },
      angular:    { name: 'Angular 19',      desc: 'Full-featured framework for SPAs developed by Google. Includes dependency injection, routing, reactive forms and native TypeScript support. Version 19 brings Signals and native control flow.', url: 'https://angular.dev/' },
      hibernate:  { name: 'Hibernate / JPA', desc: 'Primary JPA implementation for object-relational mapping (ORM) in Java. Abstracts database access, supports lazy/eager loading, second-level cache and transaction management.', url: 'https://hibernate.org/orm/documentation/' },
      jakartaee:  { name: 'Jakarta EE',      desc: 'Enterprise Java platform maintained by the Eclipse Foundation (Java EE successor). Groups specs like JSF, EJB, JPA, JAX-RS, CDI and JDBC for robust enterprise application development.', url: 'https://jakarta.ee/learn/docs/' }
    },

    // ── Child Meta ──
    childMeta: {
      'Spring Boot':       { desc: 'Framework simplifying standalone Java app creation with minimal configuration (convention over configuration). Ideal for microservices and REST APIs with embedded Tomcat/Netty server.', url: 'https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/' },
      'Spring Security':   { desc: 'Authentication and authorization framework for Spring. Supports OAuth2, JWT, LDAP and identity providers like Keycloak for granular access control.', url: 'https://docs.spring.io/spring-security/reference/' },
      'Spring Data JPA':   { desc: 'Spring module simplifying data access with JPA. Auto-generates repository implementations from interfaces, eliminating persistence boilerplate.', url: 'https://docs.spring.io/spring-data/jpa/reference/' },
      'Spring MVC':        { desc: 'Spring web MVC framework for REST APIs and web applications. Based on Model-View-Controller with annotations like @RestController, @RequestMapping and @PathVariable.', url: 'https://docs.spring.io/spring-framework/reference/web/webmvc.html' },
      'Spring Cloud':      { desc: 'Toolset for distributed systems patterns: service discovery (Eureka), API Gateway, circuit breaker (Resilience4j), config server and load balancing.', url: 'https://spring.io/projects/spring-cloud' },
      'JSF':               { desc: 'JavaServer Faces — component-oriented MVC framework for web UIs in Java EE/Jakarta EE. Foundation of the PrimeFaces ecosystem, with a container-managed lifecycle.', url: 'https://jakarta.ee/specifications/faces/' },
      'EJB':               { desc: 'Enterprise JavaBeans — server-side components for transactional business logic. Supports stateless, stateful and message-driven beans managed by the Jakarta EE container.', url: 'https://jakarta.ee/specifications/enterprise-beans/' },
      'JDBC':              { desc: 'Java Database Connectivity — standard Java API for connecting to relational databases via drivers. Foundation for ORM frameworks like Hibernate and Spring Data JDBC.', url: 'https://docs.oracle.com/en/java/javase/17/docs/api/java.sql/module-summary.html' },
      'JUnit':             { desc: 'Most widely used unit testing framework for Java. Version 5 (Jupiter) brings expressive annotations, extensions, parameterized tests and native Java 8+ support.', url: 'https://junit.org/junit5/docs/current/user-guide/' },
      'Mockito':           { desc: 'Mocking framework for Java tests. Creates simulated objects (mocks/stubs/spies) and verifies interactions, isolating external dependencies for precise unit tests.', url: 'https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html' },
      'PrimeFaces':        { desc: 'Rich component library for JSF with 100+ ready-made components: dynamic tables, charts, calendars, dialogs and file upload, with customizable themes.', url: 'https://primefaces.org/documentation/' },
      'Tailwind CSS':      { desc: 'Utility-first CSS framework for styling directly in HTML with utility classes. Eliminates excessive custom CSS, is highly configurable and has native dark mode support.', url: 'https://tailwindcss.com/docs/' },
      'Bootstrap':         { desc: 'Responsive CSS framework with a grid system, ready-made components (navbars, modals, cards, alerts) and layout utilities for rapidly building consistent interfaces.', url: 'https://getbootstrap.com/docs/' },
      'HTML5':             { desc: 'Fifth version of the web markup language. Introduced semantics (article, section, header), native APIs like Canvas, WebStorage and Geolocation, and improved accessibility support.', url: 'https://developer.mozilla.org/en-US/docs/Web/HTML' },
      'CSS3':              { desc: 'Third version of Cascading Style Sheets. Brought flexbox, grid, animations, transitions, CSS variables and media queries for styling modern, responsive interfaces.', url: 'https://developer.mozilla.org/en-US/docs/Web/CSS' },
      'SPA':               { desc: 'Single Page Application — architectural pattern where a single HTML page loads the entire application, dynamically updating content via JavaScript without full page reloads.', url: 'https://developer.mozilla.org/en-US/docs/Glossary/SPA' },
      'Oracle':            { desc: 'Leading enterprise relational DBMS with high scalability, PL/SQL support and advanced features like RAC (high availability), Data Guard (disaster recovery) and In-Memory.', url: 'https://docs.oracle.com/en/database/oracle/oracle-database/21/' },
      'PostgreSQL':        { desc: 'Most advanced open-source relational DBMS, with support for advanced data types (JSON, arrays, hstore), extensions like PostGIS and excellent SQL standard compliance.', url: 'https://www.postgresql.org/docs/' },
      'MySQL':             { desc: "World's most used open-source relational database, widely adopted in web applications with good performance, transaction support (InnoDB) and replication.", url: 'https://dev.mysql.com/doc/' },
      'Modelagem Relacional': { desc: 'Structuring data in tables with relationships defined by primary and foreign keys. The foundation of any relational database, ensuring referential data integrity.', url: 'https://learn.microsoft.com/en-us/office/troubleshoot/access/database-normalization-description' },
      'Normalização':      { desc: 'Process of organizing tables to reduce redundancy and dependencies. Involves normal forms (1NF, 2NF, 3NF, BCNF) to ensure database consistency and efficiency.', url: 'https://learn.microsoft.com/en-us/office/troubleshoot/access/database-normalization-description' },
      'Otimização de Queries': { desc: 'Techniques to improve SQL query performance: strategic index use, EXPLAIN PLAN, complex query rewriting, avoiding N+1 and database parameter tuning.', url: 'https://www.postgresql.org/docs/current/performance-tips.html' },
      'Índices e Performance': { desc: 'Structures that speed up database searches. Types: B-tree, Hash, GIN, BRIN. Strategic use avoids full table scans and drastically reduces query response times.', url: 'https://use-the-index-luke.com/' },
      'AWS':               { desc: "World's largest cloud platform with 200+ services: EC2 (compute), S3 (storage), RDS (managed DB), Lambda (serverless), EKS (managed Kubernetes) and much more.", url: 'https://docs.aws.amazon.com/' },
      'Azure':             { desc: "Microsoft's cloud platform with strong integration into the .NET and Microsoft 365 ecosystems. Offers AKS, Azure Functions, Azure DevOps, Active Directory and CI/CD pipelines.", url: 'https://learn.microsoft.com/en-us/azure/' },
      'Google Cloud Platform (GCP)': { desc: "Google's data and AI-focused cloud platform. Highlights: BigQuery, Cloud Run, GKE (Kubernetes), Cloud Functions, Vertex AI and native Firebase integration.", url: 'https://cloud.google.com/docs' },
      'Firebase':          { desc: "Google's platform for app development with real-time database (Firestore), integrated authentication, hosting, cloud functions, storage and analytics.", url: 'https://firebase.google.com/docs' },
      'Docker':            { desc: 'Containerization platform that packages applications and dependencies into portable containers. Ensures consistency across dev, staging and production environments, simplifying deploys.', url: 'https://docs.docker.com/' },
      'Kubernetes':        { desc: 'Open-source container orchestration platform developed by Google. Automates deployment, horizontal scaling and management of applications in clusters.', url: 'https://kubernetes.io/docs/home/' },
      'Git':               { desc: "World's most widely used distributed version control system. Tracks code changes, manages branches, merges alterations and enables efficient team collaboration.", url: 'https://git-scm.com/doc' },
      'GitHub':            { desc: "Largest Git-based code hosting platform. Offers repositories, pull requests, collaborative code review, GitHub Actions for CI/CD and GitHub Packages.", url: 'https://docs.github.com/en' },
      'Bitbucket':         { desc: 'Atlassian code hosting platform with native Jira and Confluence integration. Supports Git, integrated CI/CD pipelines and granular access control per team.', url: 'https://support.atlassian.com/bitbucket-cloud/' },
      'GitHub Actions':    { desc: 'CI/CD platform integrated into GitHub. Automates build, test and deploy workflows with YAML files in the repository, offering a reusable actions marketplace.', url: 'https://docs.github.com/en/actions' },
      'Azure DevOps':      { desc: 'Microsoft DevOps suite with Boards (agile management), Repos (Git), Pipelines (CI/CD), Test Plans and Artifacts. Strong Azure and Microsoft ecosystem integration.', url: 'https://learn.microsoft.com/en-us/azure/devops/' },
      'Pipelines':         { desc: 'CI/CD pipelines automate the complete build, test and deploy flow. They ensure continuous quality delivery, integrating tools like GitHub Actions and Azure DevOps.', url: 'https://docs.github.com/en/actions/writing-workflows' },
      'RabbitMQ (AMQP)':   { desc: 'Open-source message broker implementing the AMQP protocol. Enables asynchronous communication between microservices with queues, exchanges, routing and message delivery guarantees.', url: 'https://www.rabbitmq.com/documentation.html' },
      'REST APIs':         { desc: 'API architecture based on REST principles: resources identified by URLs, HTTP verbs (GET/POST/PUT/DELETE), stateless and JSON/XML responses. Dominant standard for system integration.', url: 'https://restfulapi.net/' },
      'Apache HTTP Server':{ desc: "World's most widely used open-source web server. Supports modules like mod_proxy (reverse proxy), mod_ssl (HTTPS), mod_rewrite (friendly URLs) and virtual hosts for multiple domains.", url: 'https://httpd.apache.org/docs/' },
      'WildFly':           { desc: "Red Hat's open-source Jakarta EE application server. Supports EJB, JPA, JAX-RS and CDI. JBoss EAP is the enterprise-certified version with commercial support for production.", url: 'https://docs.wildfly.org/' },
      'JBoss EAP':         { desc: 'Red Hat JBoss Enterprise Application Platform — enterprise version of WildFly with Red Hat support, security patches, certifications and additional features for critical production environments.', url: 'https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/' },
      'OAuth2':            { desc: 'Open authorization protocol (RFC 6749) enabling delegated resource access without sharing credentials. Standard for modern authentication in REST APIs and Single Page Applications.', url: 'https://oauth.net/2/' },
      'OpenID Connect':    { desc: 'Identity layer built on top of OAuth2 that adds federated authentication. Returns user information via JWT-format ID Token, enabling SSO across systems.', url: 'https://openid.net/connect/' },
      'SSO':               { desc: 'Single Sign-On — the user authenticates once and accesses multiple systems without logging in again. Implemented via Keycloak with OpenID Connect to centralize corporate identity.', url: 'https://www.keycloak.org/docs/latest/server_admin/#sso-protocols' },
      'JWT':               { desc: 'JSON Web Token (RFC 7519) — standard for securely transmitting information between parties as a digitally signed JSON. Widely used for stateless authentication in RESTful APIs.', url: 'https://jwt.io/introduction/' },
      'Role-based Access Control': { desc: 'RBAC: users have permissions assigned via roles (e.g., ADMIN, USER). Implemented with @PreAuthorize and @Secured in Spring Security for fine-grained authorization.', url: 'https://docs.spring.io/spring-security/reference/servlet/authorization/method-security.html' },
      'Microsserviços':    { desc: 'Architectural style where the application is decomposed into small, independent and separately deployable services. Each service has its own responsibility, database and deploy cycle.', url: 'https://microservices.io/' },
      'Clean Architecture':{ desc: "Architecture proposed by Robert C. Martin organizing code in concentric layers (Entities, Use Cases, Adapters, Frameworks), ensuring independence from frameworks, UI and database.", url: 'https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html' },
      'Arquitetura Hexagonal': { desc: 'Also called Ports & Adapters, isolates the domain from external dependencies (UI, DB, APIs) through well-defined interfaces. Simplifies swapping implementations and unit testing.', url: 'https://alistair.cockburn.us/hexagonal-architecture/' },
      'MVC':               { desc: 'Model-View-Controller — pattern separating the application into three layers: Model (data and rules), View (interface) and Controller (control flow). Foundation of Spring MVC and Angular.', url: 'https://developer.mozilla.org/en-US/docs/Glossary/MVC' },
      'SOLID':             { desc: 'Five OO design principles: Single Responsibility, Open/Closed, Liskov Substitution, Interface Segregation and Dependency Inversion. Guide for cohesive, extensible and testable code.', url: 'https://www.digitalocean.com/community/conceptual-articles/s-o-l-i-d-the-first-five-principles-of-object-oriented-design' },
      'Clean Code':        { desc: 'Practices for readable and maintainable code, popularized by Robert C. Martin. Focuses on meaningful names, small single-responsibility functions and absence of duplication.', url: 'https://www.oreilly.com/library/view/clean-code-a/9780136083238/' },
      'TDD':               { desc: 'Test-Driven Development — methodology where the test is written before the production code. Cycle: Red (test fails) → Green (minimal code passes) → Refactor (improve without breaking tests).', url: 'https://martinfowler.com/bliki/TestDrivenDevelopment.html' },
      'BDD':               { desc: 'Behavior-Driven Development — TDD extension describing system behavior in natural language (Gherkin: Given/When/Then). Bridges developers, QA and stakeholders through executable specifications.', url: 'https://cucumber.io/docs/bdd/' },
      'Scrum':             { desc: 'Iterative and incremental agile framework with roles (Product Owner, Scrum Master, Dev Team), ceremonies (Planning, Daily, Review, Retrospective) and artifacts (Product Backlog, Sprint Backlog).', url: 'https://www.scrum.org/resources/what-is-scrum' },
      'Kanban':            { desc: 'Visual agile workflow management method originated at Toyota. Uses boards with columns (To Do, In Progress, Done) and limits WIP (Work in Progress) to maximize throughput.', url: 'https://www.atlassian.com/agile/kanban' },
      'Jira':              { desc: "Atlassian's agile project management platform. Supports Scrum and Kanban, sprints, backlogs, epics, velocity reports and integration with CI/CD and code repositories.", url: 'https://support.atlassian.com/jira-software-cloud/' },
      'Trello':            { desc: "Atlassian's visual task management tool based on Kanban. Organizes projects into boards, lists and cards with Butler automations, power-ups and real-time collaboration.", url: 'https://support.atlassian.com/trello/' },
      'SonarQube':         { desc: 'Continuous code quality inspection platform. Detects bugs, vulnerabilities, code smells and calculates technical debt. Integrates into CI/CD with automatic Quality Gates.', url: 'https://docs.sonarqube.org/latest/' },
      'Code Review':       { desc: 'Peer code review before merge. Improves quality, spreads knowledge within the team, identifies bugs early and ensures adherence to coding standards.', url: 'https://google.github.io/eng-practices/review/' },
      'Pair Programming':  { desc: "XP practice where two developers work together: the 'driver' writes the code and the 'navigator' reviews in real time. Reduces errors, accelerates learning and improves code quality.", url: 'https://martinfowler.com/articles/on-pair-programming.html' },
      'Swagger/OpenAPI':   { desc: 'Tools for REST API design, documentation and testing. The OpenAPI specification describes APIs in a standardized way, auto-generating interactive documentation and clients.', url: 'https://swagger.io/docs/' },
      'Figma':             { desc: 'Cloud-based collaborative design tool for creating interfaces, prototypes and design systems. Enables real-time collaboration between designers and developers.', url: 'https://help.figma.com/' },
      'UML':               { desc: 'Unified Modeling Language — standard modeling language for visualizing and documenting software systems with class, sequence, use case, component and deployment diagrams.', url: 'https://www.uml.org/' },
      'Slack':             { desc: 'Team communication platform with organized channels, direct messages, video calls and integration with GitHub, Jira, CI/CD and hundreds of development tools.', url: 'https://slack.com/help' },
      'Microsoft Teams':   { desc: 'Microsoft collaboration platform integrated with Office 365. Offers chat, video calls, project channels and native integration with SharePoint, OneDrive and Azure DevOps.', url: 'https://learn.microsoft.com/en-us/microsoftteams/' },
      'Google Workspace':  { desc: "Google's productivity and collaboration suite with Gmail, Drive, Docs, Sheets, Meet and Calendar. Widely used by development teams for communication and documentation.", url: 'https://workspace.google.com/' },
      'JasperReports':     { desc: "TIBCO's open-source Java library for generating reports in PDF, Excel, HTML and other formats from JRXML templates. Integrates with Spring and any data source.", url: 'https://community.jaspersoft.com/documentation/' }
    }
  },

  // ════════════════════════════════════════════════════════════
  // ESPAÑOL
  // ════════════════════════════════════════════════════════════
  es: {
    // ── UI ──
    'profile-role'   : 'Desarrollador de Sistemas',
    'bio'            : 'Especialización en Ingeniería de Software por la UFPR. Trabajo desde el back-end Java/Spring hasta el front-end React/Angular, con foco en Clean Code, microservicios y buenas prácticas.',
    'greeting'       : 'Bienvenido a mi portafolio',
    'headline'       : 'Hola, soy <span class="accent">Gustavo</span>',
    'description'    : 'Un entusiasta de la tecnología,<br>te invito a conocer un poco sobre mi trabajo.<br>Participo en proyectos desde la <strong>definición de las reglas de negocio</strong> hasta el build y el deploy. Tengo sólida experiencia con el <strong>back-end Java/Spring</strong> y <strong>front-end JS/React</strong>, con arquitecturas monolíticas y de microservicios, cloud y buenas prácticas de ingeniería de software.',
    'btn-primary'    : 'Ver Proyectos',
    'section-title'  : 'Competencias y conocimientos técnicos',
    'section-subtitle': 'Haz clic en cualquier tecnología para aprender más y ver la documentación',
    'modal-link'     : 'Ver documentación oficial',
    'page-title'     : 'Portafolio — Gustavo Ramos',

    // ── Category names ──
    'Linguagens de Programação' : 'Lenguajes de Programación',
    'Bancos de Dados'           : 'Bases de Datos',
    'Mensageria & Servidores'   : 'Mensajería & Servidores',
    'Autenticação & Segurança'  : 'Autenticación & Seguridad',
    'Arquiteturas & Padrões'    : 'Arquitecturas & Patrones',
    'Ferramentas & Metodologias': 'Herramientas & Metodologías',

    // ── Group labels ──
    'Testes'                : 'Pruebas',
    'Bibliotecas de UI'     : 'Librerías de UI',
    'Fundamentos Web'       : 'Fundamentos Web',
    'SGBDs Relacionais'     : 'SGBDs Relacionales',
    'Práticas'              : 'Prácticas',
    'Versionamento'         : 'Control de Versiones',
    'Servidores de Aplicação': 'Servidores de Aplicación',
    'Mensageria'            : 'Mensajería',
    'Arquiteturas'          : 'Arquitecturas',
    'Boas Práticas'         : 'Buenas Prácticas',
    'Gestão Ágil'           : 'Gestión Ágil',
    'Qualidade de Código'   : 'Calidad de Código',
    'Documentação & Design' : 'Documentación & Diseño',
    'Colaboração'           : 'Colaboración',
    'Relatórios'            : 'Informes',

    // ── Child names ──
    'Microsserviços'         : 'Microservicios',
    'Arquitetura Hexagonal'  : 'Arquitectura Hexagonal',
    'Modelagem Relacional'   : 'Modelado Relacional',
    'Normalização'           : 'Normalización',
    'Otimização de Queries'  : 'Optimización de Queries',
    'Índices e Performance'  : 'Índices y Rendimiento',

    // ── Skill Docs ──
    skillDocs: {
      java:       { name: 'Java 8–25',       desc: 'Lenguaje orientado a objetos, fuertemente tipado y multiplataforma, base del ecosistema enterprise. Las versiones 8–17 introdujeron lambdas, Streams API, records, clases selladas y pattern matching.', url: 'https://docs.oracle.com/en/java/javase/17/' },
      javascript: { name: 'JavaScript ES6+', desc: 'Lenguaje ligero e interpretado esencial para el desarrollo web. Soporta POO, programación funcional y asíncrona (Promises/async-await). Ejecuta en el navegador y en el servidor (Node.js).', url: 'https://developer.mozilla.org/es/docs/Web/JavaScript' },
      typescript: { name: 'TypeScript',      desc: 'Superset tipado de JavaScript desarrollado por Microsoft. Agrega tipado estático, interfaces, enums y genéricos, haciendo proyectos a gran escala más seguros y mantenibles.', url: 'https://www.typescriptlang.org/docs/' },
      sql:        { name: 'SQL / PL-SQL',    desc: 'SQL es el lenguaje estándar para bases de datos relacionales. PL/SQL es la extensión procedural de Oracle, utilizada en stored procedures, funciones, triggers y paquetes corporativos.', url: 'https://docs.oracle.com/en/database/oracle/oracle-database/21/lnpls/' },
      react:      { name: 'React',           desc: 'Librería JavaScript para construir interfaces basadas en componentes reutilizables. Creada por Meta, usa Virtual DOM; el ecosistema incluye React Router, Context API, hooks y Server Components.', url: 'https://react.dev/' },
      angular:    { name: 'Angular 19',      desc: 'Framework completo para SPAs desarrollado por Google. Incluye inyección de dependencias, enrutamiento, formularios reactivos y soporte nativo para TypeScript. La versión 19 trae Signals y control flow nativo.', url: 'https://angular.dev/' },
      hibernate:  { name: 'Hibernate / JPA', desc: 'Principal implementación JPA para mapeo objeto-relacional (ORM) en Java. Abstrae el acceso a BD, soporta lazy/eager loading, caché de segundo nivel y gestión de transacciones.', url: 'https://hibernate.org/orm/documentation/' },
      jakartaee:  { name: 'Jakarta EE',      desc: 'Plataforma enterprise Java mantenida por la Eclipse Foundation (sucesora de Java EE). Agrupa especificaciones como JSF, EJB, JPA, JAX-RS, CDI y JDBC para el desarrollo de aplicaciones corporativas robustas.', url: 'https://jakarta.ee/learn/docs/' }
    },

    // ── Child Meta ──
    childMeta: {
      'Spring Boot':       { desc: 'Framework que simplifica la creación de aplicaciones Java standalone con configuración mínima (convention over configuration). Ideal para microservicios y APIs REST con servidor embebido Tomcat/Netty.', url: 'https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/' },
      'Spring Security':   { desc: 'Framework de autenticación y autorización para Spring. Soporta OAuth2, JWT, LDAP e integración con proveedores de identidad como Keycloak para control de acceso granular.', url: 'https://docs.spring.io/spring-security/reference/' },
      'Spring Data JPA':   { desc: 'Módulo de Spring que simplifica el acceso a datos con JPA. Genera implementaciones de repositorios automáticamente desde interfaces, eliminando el boilerplate de persistencia.', url: 'https://docs.spring.io/spring-data/jpa/reference/' },
      'Spring MVC':        { desc: 'Framework web MVC de Spring para APIs REST y aplicaciones web. Basado en el patrón Model-View-Controller con anotaciones como @RestController, @RequestMapping y @PathVariable.', url: 'https://docs.spring.io/spring-framework/reference/web/webmvc.html' },
      'Spring Cloud':      { desc: 'Conjunto de herramientas para patrones de sistemas distribuidos: service discovery (Eureka), API Gateway, circuit breaker (Resilience4j), config server y load balancing.', url: 'https://spring.io/projects/spring-cloud' },
      'JSF':               { desc: 'JavaServer Faces — framework MVC orientado a componentes para UIs web en Java EE/Jakarta EE. Base del ecosistema PrimeFaces, con ciclo de vida gestionado por el container.', url: 'https://jakarta.ee/specifications/faces/' },
      'EJB':               { desc: 'Enterprise JavaBeans — componentes del lado servidor para lógica de negocio transaccional. Soporta beans stateless, stateful y message-driven, gestionados por el container Jakarta EE.', url: 'https://jakarta.ee/specifications/enterprise-beans/' },
      'JDBC':              { desc: 'Java Database Connectivity — API estándar de Java para conectar con bases de datos relacionales mediante drivers. Base para frameworks ORM como Hibernate y Spring Data JDBC.', url: 'https://docs.oracle.com/en/java/javase/17/docs/api/java.sql/module-summary.html' },
      'JUnit':             { desc: 'Framework de pruebas unitarias más utilizado en Java. La versión 5 (Jupiter) trae anotaciones expresivas, extensiones, pruebas parametrizadas y soporte nativo a Java 8+.', url: 'https://junit.org/junit5/docs/current/user-guide/' },
      'Mockito':           { desc: 'Framework de mocking para pruebas en Java. Crea objetos simulados (mocks/stubs/spies) y verifica interacciones, aislando dependencias externas para pruebas unitarias precisas.', url: 'https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html' },
      'PrimeFaces':        { desc: 'Librería de componentes ricos para JSF con más de 100 componentes listos: tablas dinámicas, gráficos, calendarios, dialogs y carga de archivos, con temas personalizables.', url: 'https://primefaces.org/documentation/' },
      'Tailwind CSS':      { desc: 'Framework CSS utility-first para estilizar directamente en HTML con clases utilitarias. Elimina CSS personalizado excesivo, es altamente configurable y tiene soporte nativo a dark mode.', url: 'https://tailwindcss.com/docs/' },
      'Bootstrap':         { desc: 'Framework CSS responsivo con sistema de grid, componentes listos (navbars, modales, cards, alertas) y utilidades de diseño para crear interfaces consistentes rápidamente.', url: 'https://getbootstrap.com/docs/' },
      'HTML5':             { desc: 'Quinta versión del lenguaje de marcado de la web. Introdujo semántica (article, section, header), APIs nativas como Canvas, WebStorage y Geolocalización, y mejor soporte de accesibilidad.', url: 'https://developer.mozilla.org/es/docs/Web/HTML' },
      'CSS3':              { desc: 'Tercera versión de las Hojas de Estilo en Cascada. Trajo flexbox, grid, animaciones, transiciones, variables CSS y media queries para estilizar interfaces modernas y responsivas.', url: 'https://developer.mozilla.org/es/docs/Web/CSS' },
      'SPA':               { desc: 'Single Page Application — patrón arquitectónico donde una única página HTML carga toda la aplicación, actualizando dinámicamente el contenido via JavaScript sin recargar la página.', url: 'https://developer.mozilla.org/en-US/docs/Glossary/SPA' },
      'Oracle':            { desc: 'SGBD relacional líder empresarial con alta escalabilidad, soporte a PL/SQL y características avanzadas como RAC (alta disponibilidad), Data Guard (disaster recovery) e In-Memory.', url: 'https://docs.oracle.com/en/database/oracle/oracle-database/21/' },
      'PostgreSQL':        { desc: 'SGBD relacional open-source más avanzado, con soporte para tipos de datos avanzados (JSON, arrays, hstore), extensiones como PostGIS y excelente conformidad con el estándar SQL.', url: 'https://www.postgresql.org/docs/' },
      'MySQL':             { desc: 'Base de datos relacional open-source más utilizada en el mundo, ampliamente adoptada en aplicaciones web con buen rendimiento, soporte a transacciones (InnoDB) y replicación.', url: 'https://dev.mysql.com/doc/' },
      'Modelagem Relacional': { desc: 'Estructuración de datos en tablas con relaciones definidas por claves primarias y foráneas. La base de cualquier BD relacional, garantizando la integridad referencial de los datos.', url: 'https://learn.microsoft.com/es-es/office/troubleshoot/access/database-normalization-description' },
      'Normalização':      { desc: 'Proceso de organización de tablas para reducir redundancia y dependencias. Involucra las formas normales (1FN, 2FN, 3FN, BCNF) para garantizar consistencia y eficiencia de la BD.', url: 'https://learn.microsoft.com/es-es/office/troubleshoot/access/database-normalization-description' },
      'Otimização de Queries': { desc: 'Técnicas para mejorar el rendimiento de consultas SQL: uso estratégico de índices, EXPLAIN PLAN, reescritura de queries complejas, evitar N+1 y ajuste de parámetros de la BD.', url: 'https://www.postgresql.org/docs/current/performance-tips.html' },
      'Índices e Performance': { desc: 'Estructuras que aceleran búsquedas en bases de datos. Tipos: B-tree, Hash, GIN, BRIN. El uso estratégico evita full table scans y reduce drásticamente el tiempo de respuesta de queries.', url: 'https://use-the-index-luke.com/' },
      'AWS':               { desc: 'Mayor plataforma cloud del mundo con +200 servicios: EC2 (cómputo), S3 (almacenamiento), RDS (BD gestionada), Lambda (serverless), EKS (Kubernetes gestionado) y mucho más.', url: 'https://docs.aws.amazon.com/' },
      'Azure':             { desc: 'Plataforma cloud de Microsoft con fuerte integración al ecosistema .NET y Microsoft 365. Ofrece AKS, Azure Functions, Azure DevOps, Active Directory y pipelines de CI/CD.', url: 'https://learn.microsoft.com/es-es/azure/' },
      'Google Cloud Platform (GCP)': { desc: 'Plataforma cloud de Google enfocada en datos e IA. Destacados: BigQuery, Cloud Run, GKE (Kubernetes), Cloud Functions, Vertex AI e integración nativa con Firebase.', url: 'https://cloud.google.com/docs' },
      'Firebase':          { desc: 'Plataforma de Google para desarrollo de apps con BD en tiempo real (Firestore), autenticación integrada, hosting, cloud functions, storage y analytics.', url: 'https://firebase.google.com/docs' },
      'Docker':            { desc: 'Plataforma de contenedores que empaqueta aplicaciones y dependencias en contenedores portátiles. Garantiza consistencia entre entornos dev, staging y producción, facilitando deploys.', url: 'https://docs.docker.com/' },
      'Kubernetes':        { desc: 'Plataforma open-source de orquestación de contenedores desarrollada por Google. Automatiza el despliegue, escalado horizontal y gestión de aplicaciones en clústeres.', url: 'https://kubernetes.io/docs/home/' },
      'Git':               { desc: 'Sistema de control de versiones distribuido más utilizado del mundo. Permite rastrear cambios en el código, crear branches, fusionar alteraciones y colaborar eficientemente en equipo.', url: 'https://git-scm.com/doc' },
      'GitHub':            { desc: 'Mayor plataforma de alojamiento de código basada en Git. Ofrece repositorios, pull requests, code review colaborativo, GitHub Actions para CI/CD y GitHub Packages.', url: 'https://docs.github.com/es' },
      'Bitbucket':         { desc: 'Plataforma de alojamiento de código de Atlassian con integración nativa a Jira y Confluence. Soporta Git, pipelines de CI/CD integrados y control de acceso granular por equipos.', url: 'https://support.atlassian.com/bitbucket-cloud/' },
      'GitHub Actions':    { desc: 'Plataforma de CI/CD integrada en GitHub. Automatiza workflows de build, pruebas y deploy con archivos YAML en el repositorio, ofreciendo un marketplace de actions reutilizables.', url: 'https://docs.github.com/es/actions' },
      'Azure DevOps':      { desc: 'Suite DevOps de Microsoft con Boards (gestión ágil), Repos (Git), Pipelines (CI/CD), Test Plans y Artifacts. Fuerte integración con Azure y el ecosistema Microsoft.', url: 'https://learn.microsoft.com/es-es/azure/devops/' },
      'Pipelines':         { desc: 'Los pipelines de CI/CD automatizan el flujo completo de build, pruebas y deploy. Garantizan entrega continua de calidad, integrando herramientas como GitHub Actions y Azure DevOps.', url: 'https://docs.github.com/es/actions/writing-workflows' },
      'RabbitMQ (AMQP)':   { desc: 'Message broker open-source que implementa el protocolo AMQP. Permite comunicación asíncrona entre microservicios con colas, exchanges, enrutamiento y garantía de entrega de mensajes.', url: 'https://www.rabbitmq.com/documentation.html' },
      'REST APIs':         { desc: 'Arquitectura de APIs basada en principios REST: recursos identificados por URLs, verbos HTTP (GET/POST/PUT/DELETE), stateless y respuestas en JSON/XML. Estándar dominante para integración de sistemas.', url: 'https://restfulapi.net/' },
      'Apache HTTP Server':{ desc: 'Servidor web open-source más utilizado del mundo. Soporta módulos como mod_proxy (proxy reverso), mod_ssl (HTTPS), mod_rewrite (URLs amigables) y virtual hosts para múltiples dominios.', url: 'https://httpd.apache.org/docs/' },
      'WildFly':           { desc: 'Servidor de aplicaciones Jakarta EE open-source de Red Hat. Soporta EJB, JPA, JAX-RS y CDI. JBoss EAP es la versión enterprise certificada con soporte comercial para producción.', url: 'https://docs.wildfly.org/' },
      'JBoss EAP':         { desc: 'Red Hat JBoss Enterprise Application Platform — versión enterprise de WildFly con soporte Red Hat, parches de seguridad, certificaciones y funcionalidades adicionales para entornos de producción críticos.', url: 'https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/' },
      'OAuth2':            { desc: 'Protocolo de autorización abierto (RFC 6749) que permite acceso delegado a recursos sin compartir credenciales. Estándar para autenticación moderna en APIs REST y Single Page Applications.', url: 'https://oauth.net/2/' },
      'OpenID Connect':    { desc: 'Capa de identidad construida sobre OAuth2 que añade autenticación federada. Devuelve información del usuario vía ID Token en formato JWT, habilitando SSO entre sistemas.', url: 'https://openid.net/connect/' },
      'SSO':               { desc: 'Single Sign-On — el usuario se autentica una vez y accede a múltiples sistemas sin nuevos logins. Implementado via Keycloak con OpenID Connect para centralizar la identidad corporativa.', url: 'https://www.keycloak.org/docs/latest/server_admin/#sso-protocols' },
      'JWT':               { desc: 'JSON Web Token (RFC 7519) — estándar para transmisión segura de información entre partes como JSON firmado digitalmente. Ampliamente usado para autenticación stateless en APIs RESTful.', url: 'https://jwt.io/introduction/' },
      'Role-based Access Control': { desc: 'RBAC: los usuarios tienen permisos asignados mediante roles (ej: ADMIN, USER). Implementado con @PreAuthorize y @Secured en Spring Security para autorización detallada.', url: 'https://docs.spring.io/spring-security/reference/servlet/authorization/method-security.html' },
      'Microsserviços':    { desc: 'Estilo arquitectónico donde la aplicación se descompone en servicios pequeños, independientes y desplegables por separado. Cada servicio tiene su responsabilidad, BD y ciclo de deploy propio.', url: 'https://microservices.io/' },
      'Clean Architecture':{ desc: 'Arquitectura propuesta por Robert C. Martin que organiza el código en capas concéntricas (Entities, Use Cases, Adapters, Frameworks), garantizando independencia de frameworks, UI y BD.', url: 'https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html' },
      'Arquitetura Hexagonal': { desc: 'También llamada Ports & Adapters, aísla el dominio de sus dependencias externas (UI, BD, APIs) mediante interfaces bien definidas. Facilita el intercambio de implementaciones y las pruebas unitarias.', url: 'https://alistair.cockburn.us/hexagonal-architecture/' },
      'MVC':               { desc: 'Model-View-Controller — patrón que separa la aplicación en tres capas: Model (datos y reglas), View (interfaz) y Controller (flujo de control). Base de frameworks como Spring MVC y Angular.', url: 'https://developer.mozilla.org/en-US/docs/Glossary/MVC' },
      'SOLID':             { desc: 'Cinco principios de diseño OO: Single Responsibility, Open/Closed, Liskov Substitution, Interface Segregation y Dependency Inversion. Guía para código cohesivo, extensible y testeable.', url: 'https://www.digitalocean.com/community/conceptual-articles/s-o-l-i-d-the-first-five-principles-of-object-oriented-design' },
      'Clean Code':        { desc: 'Conjunto de prácticas para código legible y mantenible, popularizado por Robert C. Martin. Se enfoca en nombres significativos, funciones pequeñas con responsabilidad única y ausencia de duplicación.', url: 'https://www.oreilly.com/library/view/clean-code-a/9780136083238/' },
      'TDD':               { desc: 'Test-Driven Development — metodología donde la prueba se escribe antes del código de producción. Ciclo: Red (prueba falla) → Green (código mínimo pasa) → Refactor (mejora sin romper pruebas).', url: 'https://martinfowler.com/bliki/TestDrivenDevelopment.html' },
      'BDD':               { desc: 'Behavior-Driven Development — extensión del TDD que describe comportamientos del sistema en lenguaje natural (Gherkin: Given/When/Then). Acerca desarrolladores, QA y stakeholders mediante especificaciones ejecutables.', url: 'https://cucumber.io/docs/bdd/' },
      'Scrum':             { desc: 'Framework ágil iterativo e incremental con roles (Product Owner, Scrum Master, Dev Team), ceremonias (Planning, Daily, Review, Retrospectiva) y artefactos (Product Backlog, Sprint Backlog).', url: 'https://www.scrum.org/resources/what-is-scrum' },
      'Kanban':            { desc: 'Método ágil de gestión visual del flujo de trabajo originado en Toyota. Usa tableros con columnas (To Do, In Progress, Done) y limita el WIP (Work in Progress) para maximizar el throughput.', url: 'https://www.atlassian.com/es/agile/kanban' },
      'Jira':              { desc: 'Plataforma de gestión de proyectos ágiles de Atlassian. Soporta Scrum y Kanban, sprints, backlogs, épicas, reportes de velocity e integración con CI/CD y repositorios de código.', url: 'https://support.atlassian.com/jira-software-cloud/' },
      'Trello':            { desc: 'Herramienta visual de gestión de tareas de Atlassian, basada en Kanban. Organiza proyectos en tableros, listas y tarjetas con automatizaciones Butler, power-ups y colaboración en tiempo real.', url: 'https://support.atlassian.com/trello/' },
      'SonarQube':         { desc: 'Plataforma de inspección continua de calidad de código. Detecta bugs, vulnerabilidades, code smells y calcula la deuda técnica. Se integra al CI/CD con Quality Gates automáticos.', url: 'https://docs.sonarqube.org/latest/' },
      'Code Review':       { desc: 'Revisión de código por pares antes del merge. Mejora la calidad, difunde conocimiento en el equipo, identifica bugs temprano y garantiza la adherencia a estándares de codificación.', url: 'https://google.github.io/eng-practices/review/' },
      'Pair Programming':  { desc: "Práctica XP donde dos desarrolladores trabajan juntos: el 'driver' escribe el código y el 'navigator' revisa en tiempo real. Reduce errores, acelera el aprendizaje y mejora la calidad del código.", url: 'https://martinfowler.com/articles/on-pair-programming.html' },
      'Swagger/OpenAPI':   { desc: 'Herramientas para diseño, documentación y prueba de APIs REST. La especificación OpenAPI describe APIs de forma estandarizada, generando documentación interactiva y clientes automáticamente.', url: 'https://swagger.io/docs/' },
      'Figma':             { desc: 'Herramienta de diseño colaborativo en la nube para crear interfaces, prototipos y sistemas de diseño. Permite colaboración en tiempo real entre diseñadores y desarrolladores.', url: 'https://help.figma.com/' },
      'UML':               { desc: 'Unified Modeling Language — lenguaje de modelado estándar para visualizar y documentar sistemas de software con diagramas de clases, secuencia, casos de uso, componentes y despliegue.', url: 'https://www.uml.org/' },
      'Slack':             { desc: 'Plataforma de comunicación para equipos con canales organizados, mensajes directos, videollamadas e integración con GitHub, Jira, CI/CD y cientos de herramientas de desarrollo.', url: 'https://slack.com/intl/es-es/help' },
      'Microsoft Teams':   { desc: 'Plataforma de colaboración de Microsoft integrada con Office 365. Ofrece chat, videollamadas, canales por proyecto e integración nativa con SharePoint, OneDrive y Azure DevOps.', url: 'https://learn.microsoft.com/es-es/microsoftteams/' },
      'Google Workspace':  { desc: 'Suite de productividad y colaboración de Google con Gmail, Drive, Docs, Sheets, Meet y Calendar. Ampliamente utilizada por equipos de desarrollo para comunicación y documentación.', url: 'https://workspace.google.com/' },
      'JasperReports':     { desc: 'Librería Java open-source de TIBCO para generar reportes en PDF, Excel, HTML y otros formatos a partir de templates JRXML. Se integra con Spring y cualquier fuente de datos.', url: 'https://community.jaspersoft.com/documentation/' }
    }
  }
};
